### ISSUE TITLE
NullPointerException dans IntegrationTest.java

### ISSUE THREAD

**Issue by MaximeAnsquer** [voyages-sncf-technologies/hesperides#100]
Quand je lance les tests d'intégration j'ai une `RULE.getEnvironment()` renvoie `null`ce qui provoque une  `NullPointerException` : 

```
java.lang.NullPointerException
	at io.dropwizard.client.HttpClientBuilder.<init>(HttpClientBuilder.java:87)
	at io.dropwizard.client.JerseyClientBuilder.<init>(JerseyClientBuilder.java:73)
	at integration.HesperidesClient.<init>(HesperidesClient.java:79)
	at integration.HesperidesClient.<init>(HesperidesClient.java:88)
	at integration.AbstractIntegrationTest.setup(AbstractIntegrationTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by MaximeAnsquer** [comment]
J'ai défini la variable d'environnement REDIS_CACHE_URL avec la même valeur que la variable d'environnement REDIS_URL (j'ignore si c'est correct) mais j'ai toujours la `NullPointerException`.

**Comment by Lucas-C** [comment]
Non reproductible et Redis a été supprimé de la stack de la v4
